### ISSUE TITLE
Handling of relay connections

### ISSUE THREAD

**Issue by pvanliefland** [tfoxy/graphene-django-optimizer#1]
Hello! First let me say, kudos for this library, it's a lifesaver :)

I have a question regarding Relay connections.

When I try to optimize queries involving relay connections, I get the following error:

`graphql.error.located_error.GraphQLLocatedError: 'ConnectionOptions' object has no attribute 'model'`

But AFAIK, I cannot specify a model on relay connections subclasses.

```python
class TeamConnection(relay.Connection):
    class Meta(object):
        node = TeamNode
        model = TeamMembership  # this wont work
```

Do you have any idea about how I could make this work? I'd be glad to help with a PR if you give me some directions.

**Comment by tfoxy** [comment]
Hi! I'm using this library with Apollo instead of Relay. So I didn't test how it works with Relay nodes. I'm not on a computer right now, but let me first check how can I make it work with Relay so that I can give you any directions if a PR is needed.

**Comment by tfoxy** [comment]
Hi! I detected the problem. I'm not taking into account the [Connection](https://github.com/graphql-python/graphene/blob/4346832f71564b63d6025c2c9ff88d1ffd241136/graphene/relay/connection.py#L42) type when analyzing the query.

If you want to make a PR, first, I would add two files to the tests folder: `relay_schema.py` and `test_relay.py`.
The `relay_schema.py` file should have the same content as `schema.py`, but using `interfaces = (relay.Node, )` in all types (like in http://docs.graphene-python.org/projects/django/en/latest/tutorial-relay/#schema).
The `test_relay.py` file should have the first two tests of `test_query.py`, but using the schema of `relay_schema.py`.
Finally, I would add the necessary code in `graphene_django_optimizer/query.py` to make the tests pass. Beware that that file needs refactoring, so it's not a really great code.
I think [this line](https://github.com/tfoxy/graphene-django-optimizer/blob/014b186c4d398a2f8f36ff068b4d35fab4149c75/graphene_django_optimizer/query.py#L90) is where the exception is raised. I would add a condition [here](https://github.com/tfoxy/graphene-django-optimizer/blob/014b186c4d398a2f8f36ff068b4d35fab4149c75/graphene_django_optimizer/query.py#L86) to check if the selection is an instance of the `Connection` type from `graphene.relay` and then do something similar to whats done with the `FragmentSpread`.

If you need more information, just ask me.

**Comment by tfoxy** [comment]
Hi! I just released a new version (v0.3.0) with support for relay connections. Can you check if it works for you?

**Comment by maarcingebala** [comment]
Hey, I'm testing this lib with my project and discovered another issue - I have a query using connection field but I'm also fetching `PageInfo` object which fails. Let's say I have a query like this:
```
products(before: $before, after: $after, first: $first, last: $last) {
    pageInfo {
      hasNextPage
    }
    edges {
      node {
        id
      }
    }
  }
```

The code fails in this line: https://github.com/tfoxy/graphene-django-optimizer/blob/master/graphene_django_optimizer/query.py#L110

And the error is `'ObjectTypeOptions' object has no attribute 'model'`.

I did some debugging and the node that fails is the `PageInfo` as it indeed has no `model` attribute. @tfoxy Could you validate this issue?

**Comment by tfoxy** [comment]
Hi @maarcingebala. Thanks for reporting all these issues. I really like all the detailed information.

I will add a test and fix it.

I don't have time today, but I can make time on the weekend to fix all this.

**Comment by maarcingebala** [comment]
@tfoxy Do you use optimizers with any pagination? We're also using Apollo as the client and we want to provide cursor-based pagination. But we also have queries with nested connections e.g.:
```
{
  products(first: 10) {
    edges {
      node {
        name
        variants(first: 5) {
          edges {
            node {
              name
            }
          }
        }
      }
    }
  }
}
```

Using just the ORM I'm able to fetch the data only with two DB queries:
```
Product.objects.prefetch_related('variants')
```

I'm trying to achieve the same in the API but unfortunately any pagination seems to break the prefetches as they do slicing on querysets internally which results in refetching objects that were already cached by `prefetch_related`.

**Comment by tfoxy** [comment]
When there is pagination, the default implementation of `prefetch_related` doesn't work because it only prefetches the `queryset.all()` query. This library handles different kind of querysets for `prefetch_related`, so maybe it can optimize paginations. But right now it doesn't support it.

**Comment by tfoxy** [comment]
@maarcingebala, are you sure `Product.objects.prefetch_related('variants')` works? Doesn't it fetch all the variants instead of just the first 5 from each product?

**Comment by tfoxy** [comment]
I released a new version (v0.3.1) where using `PageInfo` doesn't raise an exception.

I created a new issue about the optimization of the pagination: https://github.com/tfoxy/graphene-django-optimizer/issues/4

**Comment by maarcingebala** [comment]
Hey @tfoxy, I still have some issues with `PageInfo`. It turns out that the bug depends on the order in which you put the fields in a query. 

For example, assume that we have a `products` connection. If I put the `pageInfo` field first and then ask for the `edges`, everything works fine:
```
{
  products(first: 30) {
    pageInfo {
      hasNextPage
    }
    edges {
      node {
        id
      }
    }
  }
}
```

However, if I change the order of the two fields and put the `edges` first, the query fails:
```
{
  products(first: 30) {
    edges {
      node {
        id
      }
    }
    pageInfo {
      hasNextPage
    }
  }
}
```

Error:
```
{
  "errors": [
    {
      "message": "unsupported operand type(s) for +=: 'NoneType' and 'list'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "products"
      ]
    }
  ],
  "data": {
    "products": null
  }
}
```

According to my `pip freeze` the version I'm using is `graphene-django-optimizer==0.3.3`. Could you confirm the issue?

**Comment by tfoxy** [comment]
Fixed in v0.3.4!

**Comment by maarcingebala** [comment]
Works like a charm, thanks a lot!
